export const IGNORE_RULES_FILE_READER = Symbol("IGNORE_RULES_FILE_READER");
export const PROJECT_INVENTORY_REPOSITORY = Symbol("PROJECT_INVENTORY_REPOSITORY");
export const PROJECT_REPOSITORY = Symbol("PROJECT_REPOSITORY");
export const REPOSITORY_INVENTORY_WALKER = Symbol("REPOSITORY_INVENTORY_WALKER");
export const WORKSPACE_ROOT_RESOLVER = Symbol("WORKSPACE_ROOT_RESOLVER");
