export const IGNORE_RULES_FILE_READER = Symbol("IGNORE_RULES_FILE_READER");
export const PROJECT_REPOSITORY = Symbol("PROJECT_REPOSITORY");
export const WORKSPACE_ROOT_RESOLVER = Symbol("WORKSPACE_ROOT_RESOLVER");
